// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agqixwckqnvbdiqfdgii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFncWl4d2NrcW52YmRpcWZkZ2lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTQ4NTEsImV4cCI6MjA2MDYzMDg1MX0.C-lw4Uggv3EAsWvguL6uXkQMnmi7tXO0-bed3zfU2d4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);